version: "3"
services:
  openssl-gcp-kms:
    image: openssl-gcp-kms:latest
    hostname: openssl-kms
    user: root
    stdin_open: true
    tty: true
    volumes:
      - "${KMS_GOOGLE_APPLICATION_CREDENTIALS}:/root/.kms/google-credentials.json:ro"
      - "${KMS_PKCS11_CONFIG}:/root/.kms/pkcs11-config.yaml"
      - "./workdir:/root/google-kms"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /root/.kms/google-credentials.json
      KMS_PKCS11_CONFIG: /root/.kms/pkcs11-config.yaml
